In [ ]:
!pip install rake-nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np
from rake_nltk import Rake
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
df = pd.read_csv('/content/EdX.csv')
df.head()

Name  \
0                                How to Learn Online   
1  Programming for Everybody (Getting Started wit...   
2            CS50's Introduction to Computer Science   
3                                 The Analytics Edge   
4  Marketing Analytics: Marketing Measurement Str...   

                              University Difficulty Level  \
0                                    edX         Beginner   
1             The University of Michigan         Beginner   
2                     Harvard University         Beginner   
3  Massachusetts Institute of Technology     Intermediate   
4     University of California, Berkeley         Beginner   

                                                Link  \
0     https://www.edx.org/course/how-to-learn-online   
1  https://www.edx.org/course/programming-for-eve...   
2  https://www.edx.org/course/cs50s-introduction-...   
3      https://www.edx.org/course/the-analytics-edge   
4  https://www.edx.org/course/marketing-analytics...   

                                               About  \
0  Learn essential strategies for successful onli...   
1  This course is a "no prerequisite" introductio...   
2  An introduction to the intellectual enterprise...   
3  Through inspiring examples and stories, discov...   
4     This course is part of a MicroMasters® Program   

                                  Course Description  
0  Designed for those who are new to elearning, t...  
1  This course aims to teach everyone the basics ...  
2  This is CS50x , Harvard University's introduct...  
3  In the last decade, the amount of data availab...  
4  Begin your journey in a new career in marketin...

In [ ]:
# data overview
print('Rows x Columns : ', df.shape[0], 'x', df.shape[1])
print('Features: ', df.columns.tolist())
print('nUnique values:')
print(df.nunique())

Rows x Columns :  720 x 6
Features:  ['Name', 'University', 'Difficulty Level', 'Link', 'About', 'Course Description']
nUnique values:
Name                  717
University            102
Difficulty Level        3
Link                  719
About                 698
Course Description    717
dtype: int64


In [ ]:
# type of entries, how many missing values/null fields
df.info()
print('nMissing values:  ', df.isnull().sum().values.sum())
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Name                720 non-null    object
 1   University          720 non-null    object
 2   Difficulty Level    720 non-null    object
 3   Link                720 non-null    object
 4   About               720 non-null    object
 5   Course Description  720 non-null    object
dtypes: object(6)
memory usage: 33.9+ KB
nMissing values:   0


Name                  0
University            0
Difficulty Level      0
Link                  0
About                 0
Course Description    0
dtype: int64

In [ ]:
# to remove punctuations from Course description
import string
df['Course Description'] = df['Course Description'].str.translate(str.maketrans("","",string.punctuation))

In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# to extract key words from Course Description to a list
df['Key_words'] = ''   # initializing a new column
r = Rake()   # using Rake to remove stop words

for index, row in df.iterrows():
    r.extract_keywords_from_text(row['Course Description'])   # to extract key words 
    key_words_dict_scores = r.get_word_degrees()    # to get dictionary with key words and their similarity scores
    row['Key_words'] = list(key_words_dict_scores.keys())   # to assign it to new column

df

Name  \
0                                  How to Learn Online   
1    Programming for Everybody (Getting Started wit...   
2              CS50's Introduction to Computer Science   
3                                   The Analytics Edge   
4    Marketing Analytics: Marketing Measurement Str...   
..                                                 ...   
715         Global China: From the Mongols to the Ming   
716  Leaders in Citizen Security and Justice Manage...   
717  Computational Neuroscience: Neuronal Dynamics ...   
718  Cities and the Challenge of Sustainable Develo...   
719                      MathTrackX: Special Functions   

                                   University Difficulty Level  \
0                                         edX         Beginner   
1                  The University of Michigan         Beginner   
2                          Harvard University         Beginner   
3       Massachusetts Institute of Technology     Intermediate   
4          University of California, Berkeley         Beginner   
..                                        ...              ...   
715                        Harvard University         Beginner   
716           Inter-American Development Bank     Intermediate   
717  École polytechnique fédérale de Lausanne         Advanced   
718                               SDG Academy         Beginner   
719                    University of Adelaide         Beginner   

                                                  Link  \
0       https://www.edx.org/course/how-to-learn-online   
1    https://www.edx.org/course/programming-for-eve...   
2    https://www.edx.org/course/cs50s-introduction-...   
3        https://www.edx.org/course/the-analytics-edge   
4    https://www.edx.org/course/marketing-analytics...   
..                                                 ...   
715  https://www.edx.org/course/global-china-from-t...   
716  https://www.edx.org/course/leaders-in-citizen-...   
717  https://www.edx.org/course/computational-neuro...   
718  https://www.edx.org/course/cities-and-the-chal...   
719  https://www.edx.org/course/mathtrackx-special-...   

                                                 About  \
0    Learn essential strategies for successful onli...   
1    This course is a "no prerequisite" introductio...   
2    An introduction to the intellectual enterprise...   
3    Through inspiring examples and stories, discov...   
4       This course is part of a MicroMasters® Program   
..                                                 ...   
715  Explore the impact of the conquest dynasties a...   
716  Learn about the latest in prevention, police a...   
717  This course explains the mathematical and comp...   
718  What is a sustainable city? Learn the basics h...   
719  Understand trigonometric, exponential and loga...   

                                    Course Description  \
0    Designed for those who are new to elearning th...   
1    This course aims to teach everyone the basics ...   
2    This is CS50x  Harvard Universitys introductio...   
3    In the last decade the amount of data availabl...   
4    Begin your journey in a new career in marketin...   
..                                                 ...   
715  In the 13th century by force of arms the Mongo...   
716  The high rates of crime and violence are two o...   
717  What happens in your brain when you make a dec...   
718  According to the United Nations urbanization a...   
719  This course is part two of the MathTrackX XSer...   

                                             Key_words  
0    [designed, new, elearning, course, prepare, st...  
1    [course, aims, teach, everyone, basics, progra...  
2    [cs50x, harvard, universitys, introduction, in...  
3    [last, decade, amount, data, available, organi...  
4    [begin, journey, new, career, marketing, analy...  
..                                                 ...  
715  [13th, century, force, arms, mongols, created,...  
716  [high, r

In [ ]:
# to combine 1 lists (1 column) of key words into 1 sentence under Bag_of_words column
df['Bag_of_words'] = ''
columns = ['Key_words']

for index, row in df.iterrows():
    words = ''
    for col in columns:
        words += ' '.join(row[col]) + ' '
    row['Bag_of_words'] = words
    
# strip white spaces infront and behind, replace multiple whitespaces (if any)
df['Bag_of_words'] = df['Bag_of_words'].str.strip().str.replace('   ', ' ').str.replace('  ', ' ')

df1 = df[['Name','Bag_of_words']]

In [ ]:
df1

Name  \
0                                  How to Learn Online   
1    Programming for Everybody (Getting Started wit...   
2              CS50's Introduction to Computer Science   
3                                   The Analytics Edge   
4    Marketing Analytics: Marketing Measurement Str...   
..                                                 ...   
715         Global China: From the Mongols to the Ming   
716  Leaders in Citizen Security and Justice Manage...   
717  Computational Neuroscience: Neuronal Dynamics ...   
718  Cities and the Challenge of Sustainable Develo...   
719                      MathTrackX: Special Functions   

                                          Bag_of_words  
0    designed new elearning course prepare strategi...  
1    course aims teach everyone basics programming ...  
2    cs50x harvard universitys introduction intelle...  
3    last decade amount data available organization...  
4    begin journey new career marketing analytics l...  
..                                                 ...  
715  13th century force arms mongols created greate...  
716  high rates crime violence two main challenges ...  
717  happens brain make decision recall memory last...  
718  according united nations urbanization populati...  
719  course part two mathtrackx xseries program des...  

[720 rows x 2 columns]

In [ ]:
# to generate the count matrix
count = CountVectorizer()
count_matrix = count.fit_transform(df['Bag_of_words'])
count_matrix
cosine_sim = cosine_similarity(count_matrix, count_matrix)
print(cosine_sim)

[[1.         0.05063697 0.08890009 ... 0.08377078 0.0451754  0.06282809]
 [0.05063697 1.         0.11575623 ... 0.08483797 0.02287545 0.06362848]
 [0.08890009 0.11575623 1.         ... 0.0638334  0.02294912 0.0638334 ]
 ...
 [0.08377078 0.08483797 0.0638334  ... 1.         0.03784378 0.05263158]
 [0.0451754  0.02287545 0.02294912 ... 0.03784378 1.         0.01892189]
 [0.06282809 0.06362848 0.0638334  ... 0.05263158 0.01892189 1.        ]]


In [ ]:
indices = pd.Series(df['Name'])

In [ ]:
# this function takes in a course name as input and returns the top 5 recommended (similar) courses

def recommend(name, cosine_sim = cosine_sim):
    recommended_courses = []
    idx = indices[indices == name].index[0]   # to get the index of the movie title matching the input course
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)   # similarity scores in descending order
    top_5_indices = list(score_series.iloc[1:6].index)   # to get the indices of top 6 most similar courses
    # [1:6] to exclude 0 (index 0 is the input course itself)
    
    for i in top_5_indices: # to append the names of top 5 similar courses to the recommended_courses list
       recommended_courses.append(list(df['Name'])[i])
       #recommended_courses.sort() #for alphabetical order
    return recommended_courses


In [ ]:
recommend('The Analytics Edge')

['The Data Science Method',
 'Analyzing Data with Python',
 'Data Science and Machine Learning Capstone Project',
 'Introduction to Probability',
 'Introduction to Probability']

In [ ]:
import pickle

In [ ]:
pickle.dump(df1,open('course_df.pkl','wb'))

In [ ]:
pickle.dump(cosine_sim,open('cosine_sim.pkl','wb'))

In [ ]:
df2=pd.read_csv('/content/Coursera.csv')
df2

Course Name  \
0     Write A Feature Length Screenplay For Film Or ...   
1     Business Strategy: Business Model Canvas Analy...   
2                         Silicon Thin Film Solar Cells   
3                                  Finance for Managers   
4          Retrieve Data using Single-Table SQL Queries   
...                                                 ...   
3517  Capstone: Retrieving, Processing, and Visualiz...   
3518                   Patrick Henry: Forgotten Founder   
3519  Business intelligence and data analytics: Gene...   
3520                                Rigid Body Dynamics   
3521  Architecting with Google Kubernetes Engine: Pr...   

                                             University Difficulty Level  \
0                             Michigan State University         Beginner   
1                              Coursera Project Network         Beginner   
2                                   �cole Polytechnique         Advanced   
3                                  IESE Business School     Intermediate   
4                              Coursera Project Network         Beginner   
...                                                 ...              ...   
3517                             University of Michigan         Beginner   
3518                             University of Virginia     Intermediate   
3519                               Macquarie University         Advanced   
3520  Korea Advanced Institute of Science and Techno...         Beginner   
3521                                       Google Cloud     Intermediate   

     Course Rating                                         Course URL  \
0              4.8  https://www.coursera.org/learn/write-a-feature...   
1              4.8  https://www.coursera.org/learn/canvas-analysis...   
2              4.1  https://www.coursera.org/learn/silicon-thin-fi...   
3              4.8  https://www.coursera.org/learn/operational-fin...   
4              4.6  https://www.coursera.org/learn/single-table-sq...   
...            ...                                                ...   
3517           4.6  https://www.coursera.org/learn/python-data-vis...   
3518           4.9               https://www.coursera.org/learn/henry   
3519           4.6  https://www.coursera.org/learn/business-intell...   
3520           4.6  https://www.coursera.org/learn/rigid-body-dyna...   
3521           4.7  https://www.coursera.org/learn/deploying-secur...   

                                     Course Description  \
0     Write a Full Length Feature Film Script  In th...   
1     By the end of this guided project, you will be...   
2     This course consists of a general presentation...   
3     When it comes to numbers, there is always more...   
4     In this course you�ll learn how to effectively...   
...                                                 ...   
3517  In the capstone, students will build a series ...   
3518  �Give me liberty, or give me death:� Rememberi...   
3519  �Megatrends� heavily influence today�s organis...   
3520  This course teaches dynamics, one of the basic...   
3521  In this course, "Architecting with Google Kube...   

                                                 Skills  
0     Drama  Comedy  peering  screenwriting  film  D...  
1     Finance  business plan  persona (user experien...  
2     chemistry  physics  Solar Energy  film  lambda...  
3     accounts receivable  dupont analysis  analysis...  
4     Data Analysis  select (sql)  database manageme...  
...                                                 ...  
3517  Databases  syntax  analysis  web  Data Visuali...  
3518  retirement  Causality  career  history of the ...  
3519  analytics  tableau software  Business Intellig...  
3520  Angular  Mechanical Design  fluid mechanics  F...  
3521  bigtable  bigquery  SQL  Google Cloud Platform...  

[3522 rows x 7 columns]

In [ ]:
df3=pd.read_csv('/content/Udacity.csv')
df3

Name                        School  \
0                            Data Engineer        School of Data Science   
1                           Data Scientist        School of Data Science   
2                             Data Analyst        School of Data Science   
3                                      C++  School of Autonomous Systems   
4                          Product Manager  School of Product Management   
..                                     ...                           ...   
258               Front-End Interview Prep            Career Advancement   
259              Full-Stack Interview Prep            Career Advancement   
260  Data Structures & Algorithms in Swift            Career Advancement   
261                     iOS Interview Prep            Career Advancement   
262                      VR Interview Prep            Career Advancement   

    Difficulty Level Rating  \
0       Intermediate    4.6   
1           Advanced    4.7   
2       Intermediate    4.6   
3       Intermediate    4.6   
4           Beginner    4.7   
..               ...    ...   
258     Intermediate   None   
259     Intermediate   None   
260     Intermediate   None   
261     Intermediate   None   
262     Intermediate   None   

                                                  Link  \
0    https://www.udacity.com//course/data-engineer-...   
1    https://www.udacity.com//course/data-scientist...   
2    https://www.udacity.com//course/data-analyst-n...   
3    https://www.udacity.com//course/c-plus-plus-na...   
4    https://www.udacity.com//course/product-manage...   
..                                                 ...   
258  https://www.udacity.com//course/front-end-inte...   
259  https://www.udacity.com//course/full-stack-int...   
260  https://www.udacity.com//course/data-structure...   
261  https://www.udacity.com//course/ios-interview-...   
262  https://www.udacity.com//course/vr-interview-p...   

                                                 About  
0    Data Engineering is the foundation for the new...  
1    Build effective machine learning models, run d...  
2    Use Python, SQL, and statistics to uncover ins...  
3    Get hands-on experience by building five real-...  
4    Envision and execute the development of indust...  
..                                                 ...  
258  Answer front-end technical and behavioral inte...  
259  Answer common full stack and web security inte...  
260  Review and practice the skills technical inter...  
261  Answer iOS and mobile development interview qu...  
262  Learn how to tackle interview questions for te...  

[263 rows x 6 columns]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 61.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 16.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 85.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 kB 17.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 7.4 MB/s eta 0:00:00


SyntaxError: ignored